import { Inter } from "next/font/google";
import "./globals.css";
import Query_Client from "../components/QueryClient";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Schola Teacher",
  description: "Generated by Datastone Solutions",
  manifest: "/manifest.json",
  themeColor: "#00d7d9",
  viewport:
    "width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div id="__next">
          <Query_Client>{children}</Query_Client>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
